=== JohnKuper/Task10_MultiThreading/src/main/resources/payments.xsd
<xs:schema targetNamespace="http://www.w3schools.com/RedsDevils"
	elementFormDefault="qualified" xmlns="http://www.w3schools.com/RedsDevils"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- root element -->
	<xs:element name="PAYMENTS" type="Payments" />

	<!-- root complex type -->
	<xs:complexType name="Payments">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="payment" type="Payment" />
		</xs:sequence>
	</xs:complexType>

	<!-- Payment complex type -->
	<xs:complexType name="Payment">
		<xs:sequence>
			<xs:element minOccurs="0" name="physical_payer" type="Physical" />
			<xs:element minOccurs="0" name="physical_recipient" type="Physical" />
			<xs:element minOccurs="0" name="legal_payer" type="Legal" />
			<xs:element minOccurs="0" name="legal_recipient" type="Legal" />
			<xs:element minOccurs="0" name="details" type="Details" />
		</xs:sequence>
	</xs:complexType>

	<!-- Physical complex type -->
	<xs:complexType name="Physical">
		<xs:sequence>
			<xs:element name="bank_account" type="xs:string" />
			<xs:element name="name" type="xs:string" />
			<xs:element name="surname" type="xs:string" />
			<xs:element name="patronymic" type="xs:string" />
			<xs:element name="passport_series" type="xs:string" />
			<xs:element name="passport_number" type="xs:string" />
			<xs:element name="phone" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<!-- Legal complex type -->
	<xs:complexType name="Legal">
		<xs:sequence>
			<xs:element name="bank_account" type="xs:string" />
			<xs:element name="TIN" type="xs:string" />
			<xs:element name="company_name" type="xs:string" />
			<xs:element name="company_address" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<!-- details complex type -->
	<xs:complexType name="Details">
		<xs:sequence>
			<xs:element name="bank_BIC" type="xs:string" />
			<xs:element name="bank_name" type="xs:string" />
			<xs:element name="total" type="xs:decimal" />
			<xs:element name="date_of_payment" type="xs:date" />
			<xs:element name="date_of_execution" type="xs:date" />
			<xs:element name="payment_code" type="xs:string" />
		</xs:sequence>
	</xs:complexType>


</xs:schema>

=== JohnKuper/Task10_MultiThreading/src/main/resources/payments.xml
<?xml version="1.0" encoding="UTF-8"?>

<PAYMENTS
	xmlns="http://www.w3schools.com/RedsDevils"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com/RedsDevils payments.xsd">

	<payment>

		<physical_payer>
			<bank_account>23454613523572359010</bank_account>
			<name>Игорь</name>
			<surname>Ежов</surname>
			<patronymic>Владимирович</patronymic>
			<passport_series>5704</passport_series>
			<passport_number>465098</passport_number>
			<phone>89121904990</phone>
		</physical_payer>

		<physical_recipient>
			<bank_account>56454612357235901045</bank_account>
			<name>Олег</name>
			<surname>Шашков</surname>
			<patronymic>Михайлович</patronymic>
			<passport_series>5522</passport_series>
			<passport_number>032598</passport_number>
			<phone>89124127787</phone>
		</physical_recipient>

		<details>
			<bank_BIC>045773603</bank_BIC>
			<bank_name>SBERBANK</bank_name>
			<total>2500.50</total>
			<date_of_payment>2014-09-29</date_of_payment>
			<date_of_execution>2014-10-01</date_of_execution>
			<payment_code>003875234863945</payment_code>
		</details>

	</payment>

	<payment>

		<physical_payer>
			<bank_account>23454613523572359010</bank_account>
			<name>Алексей</name>
			<surname>Пупкин</surname>
			<patronymic>Сергеевич</patronymic>
			<passport_series>5404</passport_series>
			<passport_number>412098</passport_number>
			<phone>89121988990</phone>
		</physical_payer>

		<legal_recipient>
			<bank_account>56454612355981904444</bank_account>
			<TIN>867592757638</TIN>
			<company_name>Uncle Tony</company_name>
			<company_address>20 Broadwick Street London</company_address>
		</legal_recipient>

		<details>
			<bank_BIC>045773603</bank_BIC>
			<bank_name>SBERBANK</bank_name>
			<total>2500.50</total>
			<date_of_payment>2014-09-30</date_of_payment>
			<date_of_execution>2014-10-05</date_of_execution>
			<payment_code>003875234863945</payment_code>
		</details>

	</payment>

</PAYMENTS>
